name: Update Vector Code Map

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      mode:
        description: 'Scan mode (full/diff)'
        required: true
        default: 'diff'

jobs:
  update-vector-map:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Повна історія для режиму diff
      
      - name: Update Vector Code Map
        uses: your-org/vector-code-map@v1
        with:
          mode: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.mode || 'diff' }}
          db_type: 'chromadb'
          chroma_host: ${{ secrets.CHROMA_HOST }}
          chroma_port: '8000'
          chroma_collection: ${{ secrets.CHROMA_COLLECTION }}
          
          # Налаштування авторизації
          chroma_auth_enabled: 'true'
          chroma_auth_type: 'basic'  # або 'token', 'api_key'
          chroma_auth_credentials: ${{ secrets.CHROMA_AUTH_CREDENTIALS }}
          chroma_ssl_enabled: 'true'
          
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          file_extensions: '.js,.ts,.jsx,.tsx,.html,.css,.md,.txt'
          exclude_patterns: 'node_modules/**,dist/**,.git/**'