name: Update Vector Code Map

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      mode:
        description: 'Scan mode (full/diff)'
        required: true
        default: 'diff'

jobs:
  update-vector-map:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Повна історія для режиму diff

      - name: Update Vector Code Map
        uses: forproxyband/vector-code-map@main
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          mode: 'diff'
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          db_type: 'chromadb'
          chroma_host: ${{ secrets.CHROMADB_HOST }}
          chroma_port: ${{ secrets.CHROMADB_PORT }}
          chroma_collection: 'openai-update-vector-map'
          
          # Налаштування авторизації
          chroma_auth_enabled: 'true'
          chroma_auth_type: 'token'  # або 'token', 'api_key'
          chroma_auth_credentials: ${{ secrets.CHROMADB_TOKEN }}
          chroma_ssl_enabled: 'false'
          
          file_extensions: '.js,.ts,.jsx,.tsx,.html,.css,.md,.txt'
          exclude_patterns: 'node_modules/**,dist/**,.git/**'
